const data = {
  dices: [
    'BQADBAADcAADhdpJAAFu_XId7Vrz5gI', // 1
    'BQADBAADdAADhdpJAAEPQEZjDcU1gwI', // 2
    'BQADBAADdgADhdpJAAGh7vdjt98DiwI', // 3
    'BQADBAADeAADhdpJAAEnKztWX5P-4AI', // 4
    'BQADBAADegADhdpJAAEKtTPZsXFtIwI', // 5
    'BQADBAADfAADhdpJAAHnV60IpiYEFQI', // 6
  ],
  doges: [
    'BQADAQADAwQAAnEW1gQ2KkQ6BQxJeQI',
    'BQADAQADBQQAAnEW1gS5AnHOr0EuFgI',
    'BQADAQADFgQAAnEW1gSBy62FuIkvZwI',
    'BQADAQADGAQAAnEW1gRPrK3YFJygpQI',
    'BQADAQADGgQAAnEW1gRpEO-liqnoZwI',
    'BQADAQADHAQAAnEW1gQ2FVz6SMKEZQI',
    'BQADAQADHgQAAnEW1gSJtmO9a6mSVgI',
    'BQADAQADIAQAAnEW1gQKmsikpQLwkgI',
    'BQADAQADIgQAAnEW1gSWN4unMM4qAwI',
    'BQADAQADJAQAAnEW1gRBhsaOAhPt4QI',
    'BQADAQADJgQAAnEW1gQDkiL7KZ_rIwI',
    'BQADAQADKAQAAnEW1gSwkZuxujoneAI',
    'BQADAQADKgQAAnEW1gR-vFTgIZUKTwI',
    'BQADAQADSgQAAnEW1gSBD9_DEHR0XwI',
    'BQADAQADTAQAAnEW1gSy8loJwMxxNQI',
    'BQADAQADUwQAAnEW1gQpP3-Whki3lgI',
  ],
};

export {
  data as default,
};
